language: python
python:
        - "3.5"

os:
        - linux


before_install:
        - sudo apt-get update
        - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran git
        - sudo apt-get install build-essential
        - git clone https://github.com/swig/swig.git
        - cd swig
        - ./autogen.sh
        - ./configure
        - make
        - sudo make install
        - cd -
 
install:
        - pip install --upgrade pip
        - pip install cython
        - travis_wait pip install -r requirements.txt
        - pip install pytest-cov
        - python setup.py install
        - pip install coveralls 

script: 
    # XXX Add doctests and notebooks again
    # py.test -v --doctest-modules --cov=autoda 
    # make -C autoda test-notebooks
    - py.test -v --cov=autoda 


after_success:
        - coveralls
