language: python
python:
        - "3.5"

os:
        - linux


before_install:
        - sudo apt-get update
        - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran git
        - sudo apt-get install build-essential swig3.0
        - git clone https://github.com/automl/SMAC3 && cd SMAC3 && cat requirements.txt | xargs -n 1 -L 1 pip3 install && python3 setup.py install && cd -

install:
        - pip install --upgrade pip
        - pip install cython
        - travis_wait pip install -r requirements.txt
        - pip install pytest-cov
        - python setup.py install
        - pip install coveralls 

script: 
        - make -C autoda test-notebooks
        - py.test -v --doctest-modules --cov=autoda 

after_success:
        - coveralls
